services:
  app:
    build:
      context: .
      target: deps
    command: ["pnpm", "run", "dev"]
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  preview:
    build:
      context: .
      target: preview
    ports:
      - "4173:4173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    profiles: ["preview"]
